INSERT INTO LIB.DEPTS(ID,NAME)VALUES('1','CSE');
INSERT INTO LIB.DEPTS(ID,NAME)VALUES('2','MCE');
INSERT INTO LIB.DEPTS(ID,NAME)VALUES('3','EEE');
INSERT INTO LIB.DEPTS(ID,NAME)VALUES('4','CEE');
INSERT INTO LIB.DEPTS(ID,NAME)VALUES('5','TVE');
