/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import javax.swing.JOptionPane;

/**
 *
 * @author Sunef
 */
public class Addbooks extends javax.swing.JFrame {

    public int BID;
    public int BGID;
    public int PID;
    public int copies;
    public String BName;
    public String AName;
    public String Edition;
    public String PName;
    public String Address;
    public String Contact;
    public String Email;
    public String[] name=null;
    public int[] id=null;
    public String[] bname=null;
    public int[] bgid=null;
    int window=0;  
    /**
     * Creates new form Addbooks
     */
    public Addbooks(int i) {
        initComponents();
        fillComboBox();     
        window=i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Button_Add = new javax.swing.JButton();
        Button_cancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Edition_val = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Copies_val = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Book_list = new javax.swing.JComboBox();
        Publisher_name = new javax.swing.JTextField();
        Publisher_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Publisher_address = new javax.swing.JTextField();
        Publisher_contact = new javax.swing.JTextField();
        Publisher_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 120));
        setResizable(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("        Welcome to IUT Library Management System!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 31, 624, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 148, -1, -1));

        Button_Add.setBackground(new java.awt.Color(0, 153, 255));
        Button_Add.setForeground(new java.awt.Color(255, 255, 255));
        Button_Add.setMnemonic('a');
        Button_Add.setText("Add");
        Button_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AddActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 396, 125, -1));

        Button_cancel.setBackground(new java.awt.Color(204, 0, 0));
        Button_cancel.setForeground(new java.awt.Color(255, 255, 255));
        Button_cancel.setMnemonic('c');
        Button_cancel.setText("Cancel");
        Button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(Button_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 396, 125, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edition");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 187, -1, -1));

        Edition_val.setOpaque(true);
        jPanel1.add(Edition_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 182, 200, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. of copies");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 228, -1, -1));

        Copies_val.setOpaque(true);
        jPanel1.add(Copies_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 222, 200, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 188, -1, -1));

        Book_list.setOpaque(true);
        Book_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Book_listItemStateChanged(evt);
            }
        });
        Book_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_listActionPerformed(evt);
            }
        });
        jPanel1.add(Book_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 143, 200, -1));

        Publisher_name.setBackground(new java.awt.Color(204, 204, 204));
        Publisher_name.setForeground(new java.awt.Color(204, 0, 0));
        Publisher_name.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        Publisher_name.setEnabled(false);
        Publisher_name.setOpaque(true);
        jPanel1.add(Publisher_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 182, 210, 26));

        Publisher_id.setBackground(new java.awt.Color(204, 204, 204));
        Publisher_id.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        Publisher_id.setEnabled(false);
        Publisher_id.setOpaque(true);
        jPanel1.add(Publisher_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 142, 210, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 148, -1, -1));

        Publisher_address.setBackground(new java.awt.Color(204, 204, 204));
        Publisher_address.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        Publisher_address.setEnabled(false);
        Publisher_address.setOpaque(true);
        jPanel1.add(Publisher_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 222, 210, -1));

        Publisher_contact.setBackground(new java.awt.Color(204, 204, 204));
        Publisher_contact.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        Publisher_contact.setEnabled(false);
        Publisher_contact.setOpaque(true);
        jPanel1.add(Publisher_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 262, 210, -1));

        Publisher_email.setBackground(new java.awt.Color(204, 204, 204));
        Publisher_email.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        Publisher_email.setEnabled(false);
        Publisher_email.setOpaque(true);
        jPanel1.add(Publisher_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 302, 210, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 228, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 268, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-mail");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 308, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 255, 255));
        jLabel11.setText("Publisher Info");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 90, -1));

        jLabel12.setForeground(new java.awt.Color(0, 255, 255));
        jLabel12.setText("Book Info");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AddActionPerformed
        // TODO add your handling code here:
        boolean b=true;
        while(b==true){
            Edition=Edition_val.getText();
            copies=Integer.parseInt(Copies_val.getText());
            DB_Connect.AddBook(PID,BID,BGID,copies,BName,AName,Edition);
          
            int x=JOptionPane.showConfirmDialog(null,"Do you want to add more books?","Add Books",2,JOptionPane.QUESTION_MESSAGE);
            
            if(x==0){
                b=true;
                Edition_val.setText(null);
                Copies_val.setText(null);
            }
            else {
                b=false;
                if(window==1){
                    this.dispose();
                    Home_Admin home_admin=new Home_Admin();
                    home_admin.setVisible(true);
                }
                else {
                    this.dispose();
                    Viewbooks view=new Viewbooks();
                    view.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_Button_AddActionPerformed

    private void Button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cancelActionPerformed
        // TODO add your handling code here:
        
                if(window==1){
                    this.dispose();
                    Home_Admin home_admin=new Home_Admin();
                    home_admin.setVisible(true);
                }
                else {
                    this.dispose();
                    Viewbooks view=new Viewbooks();
                    view.setVisible(true);
                }
    }//GEN-LAST:event_Button_cancelActionPerformed

    private void Book_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Book_listItemStateChanged
        // TODO add your handling code here:
          
    }//GEN-LAST:event_Book_listItemStateChanged

    private void Book_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_listActionPerformed
        // TODO add your handling code here:
        BName=Book_list.getSelectedItem().toString();
        String[][] info_book=DB_Connect.getBookInfo();
            for(int i=0;i<info_book.length;i++){
                if(info_book[i][2].equals(BName)){
                    BGID=Integer.parseInt(info_book[i][0]);
                    break;
                }
            }
            PID=DB_Connect.getPublisherID(BGID);
            String[] info=DB_Connect.getPublisherInfo(PID);
            Publisher_id.setText(info[0]);
            Publisher_name.setText(info[1]);
            Publisher_address.setText(info[2]);
            Publisher_contact.setText(info[3]);
            Publisher_email.setText(info[4]);
    }//GEN-LAST:event_Book_listActionPerformed
    @SuppressWarnings("unchecked")
    public void fillComboBox(){
        bname=DB_Connect.getBookName();

        for(int i=0;i<bname.length;i++){
            Book_list.addItem(bname[i]);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Book_list;
    private javax.swing.JButton Button_Add;
    private javax.swing.JButton Button_cancel;
    private javax.swing.JTextField Copies_val;
    private javax.swing.JTextField Edition_val;
    private javax.swing.JTextField Publisher_address;
    private javax.swing.JTextField Publisher_contact;
    private javax.swing.JTextField Publisher_email;
    private javax.swing.JTextField Publisher_id;
    private javax.swing.JTextField Publisher_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
