/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import javax.swing.JOptionPane;

/**
 *
 * @author Sunef
 */
public class AddNewBooks extends javax.swing.JFrame {

    public String pub_type;
    public int BID;
    public int BGID;
    public int PID;
    public int copiesno;
    public String BName;
    public String AName;
    public String Edition;
    public static String[] pname=null;
    public static int[] pid=null;
  
    /**
     * Creates new form AddNewBooks
     */
    int window=0;
    public AddNewBooks(int i) {
        initComponents();
        fillComboBox();
        window=i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Book_Name = new javax.swing.JTextField();
        Author_Name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Edition_val = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        copies = new javax.swing.JTextField();
        Existing_pub = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Button_addpub = new javax.swing.JButton();
        Button_add = new javax.swing.JButton();
        Button_cancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 120));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("        Welcome to IUT Library Management System!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 31, 624, -1));

        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Book Info");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 99, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Publisher Info");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 99, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 139, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Author");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 179, -1, -1));

        Book_Name.setOpaque(true);
        jPanel1.add(Book_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 133, 200, -1));

        Author_Name.setOpaque(true);
        jPanel1.add(Author_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 173, 200, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edition");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 219, -1, -1));

        Edition_val.setOpaque(true);
        jPanel1.add(Edition_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 213, 200, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. of Copies");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 259, -1, -1));

        copies.setOpaque(true);
        jPanel1.add(copies, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 253, 201, -1));

        jPanel1.add(Existing_pub, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 134, 200, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Existing");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 139, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 173, 274, -1));

        Button_addpub.setBackground(new java.awt.Color(0, 153, 255));
        Button_addpub.setForeground(new java.awt.Color(255, 255, 255));
        Button_addpub.setMnemonic('p');
        Button_addpub.setText("Add New Publisher");
        Button_addpub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_addpubActionPerformed(evt);
            }
        });
        jPanel1.add(Button_addpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 213, 151, -1));

        Button_add.setBackground(new java.awt.Color(0, 153, 255));
        Button_add.setForeground(new java.awt.Color(255, 255, 255));
        Button_add.setMnemonic('d');
        Button_add.setText("Add");
        Button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_addActionPerformed(evt);
            }
        });
        jPanel1.add(Button_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 392, 90, -1));

        Button_cancel.setBackground(new java.awt.Color(204, 0, 0));
        Button_cancel.setForeground(new java.awt.Color(255, 255, 255));
        Button_cancel.setMnemonic('c');
        Button_cancel.setText("Cancel");
        Button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(Button_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 392, 80, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @SuppressWarnings("unchecked")
    public static void fillComboBox(){
        pname=DB_Connect.getPublisherName();
        pid=DB_Connect.getPublisherID();
        Existing_pub.removeAllItems();
        for(int i=0;i<pname.length;i++){
            Existing_pub.addItem(pname[i]);
        }
    }
    private void Button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_addActionPerformed
        // TODO add your handling code here:
        boolean b=true;
        
        while(b==true){
            BName=Book_Name.getText();
            AName=Author_Name.getText();
            Edition=Edition_val.getText();
            copiesno=Integer.parseInt(copies.getText());
            for(int i=0;i<pname.length;i++){
                    if(pname[i].equals(Existing_pub.getSelectedItem())){
                        PID=pid[i];
                    }
                }
            DB_Connect.AddNewBook(BID,PID, BGID, BName, AName,  copiesno,Edition);
        
            int x=JOptionPane.showConfirmDialog(null,"Do you want to add more books?","Add Books",2,JOptionPane.QUESTION_MESSAGE);
            
            if(x==0){
                b=true;
                
            }
            else {
                b=false;
                if(window==1){
                    this.dispose();
                    Home_Admin home_admin=new Home_Admin();
                    home_admin.setVisible(true);
                }
                else {
                    this.dispose();
                    Viewbooks view=new Viewbooks();
                    view.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_Button_addActionPerformed

    private void Button_addpubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_addpubActionPerformed
        // TODO add your handling code here:
            AddPublisher addpub=new AddPublisher(2);
            addpub.setVisible(true );
    }//GEN-LAST:event_Button_addpubActionPerformed

    private void Button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cancelActionPerformed
        // TODO add your handling code here:
                if(window==1){
                    this.dispose();
                    Home_Admin home_admin=new Home_Admin();
                    home_admin.setVisible(true);
                }
                else {
                    this.dispose();
                    Viewbooks view=new Viewbooks();
                    view.setVisible(true);
                }
    }//GEN-LAST:event_Button_cancelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Author_Name;
    private javax.swing.JTextField Book_Name;
    private javax.swing.JButton Button_add;
    private javax.swing.JButton Button_addpub;
    private javax.swing.JButton Button_cancel;
    private javax.swing.JTextField Edition_val;
    private static javax.swing.JComboBox Existing_pub;
    private javax.swing.JTextField copies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
