/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import javax.swing.JOptionPane;

/**
 *
 * @author Sunef
 */
public class AddPublisher extends javax.swing.JFrame {

    /**
     * Creates new form AddPublisher
     */
    public int PID;
    public String PName;
    public String Address;
    public String Contact;
    public String Email;
    public int window;
    public AddPublisher(int i) {
        initComponents();
        window=i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pub_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pub_address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pub_contact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pub_email = new javax.swing.JTextField();
        Button_okay = new javax.swing.JButton();
        Button_cancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 120));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Publisher Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 180, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 83, -1, -1));

        pub_name.setOpaque(true);
        jPanel1.add(pub_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 77, 200, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 123, -1, -1));

        pub_address.setOpaque(true);
        jPanel1.add(pub_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 117, 200, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 163, -1, -1));

        pub_contact.setOpaque(true);
        jPanel1.add(pub_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 157, 200, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-Mail ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 203, -1, -1));

        pub_email.setOpaque(true);
        jPanel1.add(pub_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 197, 200, -1));

        Button_okay.setBackground(new java.awt.Color(0, 153, 255));
        Button_okay.setForeground(new java.awt.Color(255, 255, 255));
        Button_okay.setMnemonic('o');
        Button_okay.setText("Okay");
        Button_okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_okayActionPerformed(evt);
            }
        });
        jPanel1.add(Button_okay, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 243, -1, -1));

        Button_cancel.setBackground(new java.awt.Color(204, 0, 0));
        Button_cancel.setForeground(new java.awt.Color(255, 255, 255));
        Button_cancel.setMnemonic('c');
        Button_cancel.setText("Cancel");
        Button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(Button_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 243, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cancelActionPerformed
        // TODO add your handling code here:
        if(window==1){
            this.dispose();
            Home_Admin home_admin=new Home_Admin();
            home_admin.setVisible(true);
        }
        else if(window==2){
            this.dispose();
        }
    }//GEN-LAST:event_Button_cancelActionPerformed

    private void Button_okayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_okayActionPerformed
        // TODO add your handling code here:
        boolean b=true;
        if(window==1){
            while(b==true){
                PName=pub_name.getText();
                Address=pub_address.getText();
                Contact=pub_contact.getText();
                Email=pub_email.getText();
                DB_Connect.AddPublisher(PName, Address, Contact, Email);
                int x=JOptionPane.showConfirmDialog(null,"Do you want to add more publishers?","Add publisher",2,JOptionPane.QUESTION_MESSAGE);

                if(x==0){
                    b=true;
                    pub_name.setText(null);
                    pub_address.setText(null);
                    pub_contact.setText(null);
                    pub_email.setText(null);

                }
                else {
                    b=false;
                    this.dispose();
                    Home_Admin home_admin=new Home_Admin();
                    home_admin.setVisible(true);
                }
            }
        }
        else {
            PName=pub_name.getText();
            Address=pub_address.getText();
            Contact=pub_contact.getText();
            Email=pub_email.getText();
            DB_Connect.AddPublisher(PName, Address, Contact, Email);
            AddNewBooks.fillComboBox();
            this.dispose();
        }
    }//GEN-LAST:event_Button_okayActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_cancel;
    private static javax.swing.JButton Button_okay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pub_address;
    private javax.swing.JTextField pub_contact;
    private javax.swing.JTextField pub_email;
    private javax.swing.JTextField pub_name;
    // End of variables declaration//GEN-END:variables
}
