/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Sunef
 */
public class Home_User extends javax.swing.JFrame {
    
    /**
     * Creates new form Home_Admin
     */
    public Home_User(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Button_Log_Out = new javax.swing.JButton();
        Button_Search = new javax.swing.JButton();
        Button_issue = new javax.swing.JButton();
        Button_return = new javax.swing.JButton();
        Button_view_issue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home-User");
        setLocation(new java.awt.Point(280, 120));
        setResizable(false);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("         Welcome to IUT Library Management System!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 624, -1));

        Button_Log_Out.setBackground(new java.awt.Color(204, 0, 0));
        Button_Log_Out.setForeground(new java.awt.Color(255, 255, 255));
        Button_Log_Out.setMnemonic('l');
        Button_Log_Out.setText("Log Out");
        Button_Log_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Log_OutActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Log_Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 414, -1, -1));

        Button_Search.setMnemonic('s');
        Button_Search.setText("Search");
        Button_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 116, 150, 60));

        Button_issue.setMnemonic('b');
        Button_issue.setText("Issue Books");
        Button_issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_issueActionPerformed(evt);
            }
        });
        jPanel1.add(Button_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 194, 150, 60));

        Button_return.setMnemonic('r');
        Button_return.setText("Return Books");
        Button_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_returnActionPerformed(evt);
            }
        });
        jPanel1.add(Button_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 194, 150, 60));

        Button_view_issue.setMnemonic('v');
        Button_view_issue.setText("View Issued Books");
        Button_view_issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_view_issueActionPerformed(evt);
            }
        });
        jPanel1.add(Button_view_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 116, 150, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Log_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Log_OutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_Button_Log_OutActionPerformed

    private void Button_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SearchActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Search search=new Search(0);
        search.setVisible(true);
    }//GEN-LAST:event_Button_SearchActionPerformed

    private void Button_issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_issueActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Issue_Books issue=new Issue_Books();
        issue.setVisible(true);
    }//GEN-LAST:event_Button_issueActionPerformed

    private void Button_view_issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_view_issueActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewIssued viewIssued=new ViewIssued();
        viewIssued.setVisible(true);
    }//GEN-LAST:event_Button_view_issueActionPerformed

    private void Button_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_returnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Return ret=new Return();
        ret.setVisible(true);
    }//GEN-LAST:event_Button_returnActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Log_Out;
    public static javax.swing.JButton Button_Search;
    private javax.swing.JButton Button_issue;
    private javax.swing.JButton Button_return;
    private javax.swing.JButton Button_view_issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
