/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

/**
 *
 * @author Sunef
 */
public class Home_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Home_Admin
     */
    public Home_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Button_Search = new javax.swing.JButton();
        Button_Addbooks = new javax.swing.JButton();
        Button_Removemem = new javax.swing.JButton();
        Button_Viewbooks = new javax.swing.JButton();
        Button_Log_Out = new javax.swing.JButton();
        Button_AddNewBooks = new javax.swing.JButton();
        Button_Addpub = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home-Admin");
        setLocation(new java.awt.Point(280, 120));
        setResizable(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("        Welcome to IUT Library Management System!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 624, -1));

        Button_Search.setMnemonic('S');
        Button_Search.setText("Search");
        Button_Search.setOpaque(true);
        Button_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 150, 60));

        Button_Addbooks.setMnemonic('c');
        Button_Addbooks.setText("Add Copies");
        Button_Addbooks.setOpaque(true);
        Button_Addbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AddbooksActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Addbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 150, 60));

        Button_Removemem.setMnemonic('m');
        Button_Removemem.setText("View Members");
        Button_Removemem.setOpaque(true);
        Button_Removemem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RemovememActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Removemem, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 150, 60));

        Button_Viewbooks.setMnemonic('b');
        Button_Viewbooks.setText("View Books");
        Button_Viewbooks.setOpaque(true);
        Button_Viewbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ViewbooksActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Viewbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 150, 60));

        Button_Log_Out.setBackground(new java.awt.Color(204, 0, 0));
        Button_Log_Out.setForeground(new java.awt.Color(255, 255, 255));
        Button_Log_Out.setMnemonic('l');
        Button_Log_Out.setText("Log Out");
        Button_Log_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Log_OutActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Log_Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 414, -1, -1));

        Button_AddNewBooks.setMnemonic('n');
        Button_AddNewBooks.setText("Add New Books");
        Button_AddNewBooks.setMaximumSize(new java.awt.Dimension(106, 28));
        Button_AddNewBooks.setMinimumSize(new java.awt.Dimension(106, 28));
        Button_AddNewBooks.setOpaque(true);
        Button_AddNewBooks.setPreferredSize(new java.awt.Dimension(106, 28));
        Button_AddNewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AddNewBooksActionPerformed(evt);
            }
        });
        jPanel1.add(Button_AddNewBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 150, 60));

        Button_Addpub.setMnemonic('p');
        Button_Addpub.setText("Add Publisher");
        Button_Addpub.setOpaque(true);
        Button_Addpub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AddpubActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Addpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 150, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel3.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SearchActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Search search=new Search(1);
        search.setVisible(true);
    }//GEN-LAST:event_Button_SearchActionPerformed

    private void Button_RemovememActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RemovememActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewMembers mem=new ViewMembers();
        mem.setVisible(true);
    }//GEN-LAST:event_Button_RemovememActionPerformed

    private void Button_Log_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Log_OutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_Button_Log_OutActionPerformed

    private void Button_AddbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AddbooksActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Addbooks addbook= new Addbooks(1);
        addbook.setVisible(true);
    }//GEN-LAST:event_Button_AddbooksActionPerformed

    private void Button_AddNewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AddNewBooksActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AddNewBooks addnewbook= new AddNewBooks(1);
        addnewbook.setVisible(true);
        
    }//GEN-LAST:event_Button_AddNewBooksActionPerformed

    private void Button_AddpubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AddpubActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AddPublisher addpub=new AddPublisher(1);
        addpub.setVisible(true );
    }//GEN-LAST:event_Button_AddpubActionPerformed

    private void Button_ViewbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ViewbooksActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Viewbooks view2=new Viewbooks();
        view2.setVisible(true);
        
    }//GEN-LAST:event_Button_ViewbooksActionPerformed


 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_AddNewBooks;
    private javax.swing.JButton Button_Addbooks;
    private javax.swing.JButton Button_Addpub;
    private javax.swing.JButton Button_Log_Out;
    private javax.swing.JButton Button_Removemem;
    public static javax.swing.JButton Button_Search;
    private javax.swing.JButton Button_Viewbooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
