/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sunef
 */
public class Issue_Books extends javax.swing.JFrame {

    public String Val;
    public int choice;
    public DefaultTableModel  dtm;
   
    public String[] Columns={"GROUP_ID","TITLE","AUTHOR","PUBLISHER","NO. OF COPIES"};
    public String[][] info=null;
    public String[] table_info=null;
    /**
     * Creates new form Issue_Books
     */
    public Issue_Books() {
        initComponents();
    }
public void Action(){
        if(RB_Author.isSelected())choice=1;
        else if(RB_Name.isSelected())choice=2;
        else if(RB_Publisher.isSelected())choice=3;
       Val=Value.getText();
      
            info=DB_Connect.getVAL(Val, choice);
            
           dtm.setColumnIdentifiers(Columns);
           for(int row=0;row<info.length;row++){
                String[] rows={ info[row][0],info[row][1],info[row][2],info[row][3],info[row][4]};
                dtm.addRow(rows);//sl No.,title,author,pubname,copy
            }
           Table_search.setModel(dtm);
      
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_search = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        RB_Author = new javax.swing.JRadioButton();
        RB_Name = new javax.swing.JRadioButton();
        RB_Publisher = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Value = new javax.swing.JTextField();
        Button_Search = new javax.swing.JButton();
        Button_Issue = new javax.swing.JButton();
        Button_Cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 120));
        setMinimumSize(new java.awt.Dimension(800, 480));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 480));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_search.setBackground(new java.awt.Color(51, 51, 51));
        Table_search.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Table_search.setForeground(new java.awt.Color(255, 255, 255));
        Table_search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Group_ID", "Title", "Author", "Publisher", "No. of Copies"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_search.setSelectionBackground(new java.awt.Color(51, 51, 51));
        Table_search.setSelectionForeground(new java.awt.Color(0, 255, 255));
        Table_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_searchMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_search);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 530, 310));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search By");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 89, -1, -1));

        buttonGroup1.add(RB_Author);
        RB_Author.setForeground(new java.awt.Color(255, 255, 255));
        RB_Author.setMnemonic('a');
        RB_Author.setText("Author Name");
        RB_Author.setContentAreaFilled(false);
        jPanel1.add(RB_Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 117, -1, -1));

        buttonGroup1.add(RB_Name);
        RB_Name.setForeground(new java.awt.Color(255, 255, 255));
        RB_Name.setMnemonic('b');
        RB_Name.setText("Book Name");
        RB_Name.setContentAreaFilled(false);
        jPanel1.add(RB_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 141, -1, -1));

        buttonGroup1.add(RB_Publisher);
        RB_Publisher.setForeground(new java.awt.Color(255, 255, 255));
        RB_Publisher.setMnemonic('p');
        RB_Publisher.setText("Publisher");
        RB_Publisher.setContentAreaFilled(false);
        jPanel1.add(RB_Publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 165, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Value");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 195, -1, -1));

        Value.setOpaque(true);
        jPanel1.add(Value, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, -1));

        Button_Search.setMnemonic('s');
        Button_Search.setText("Search");
        Button_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 269, 140, -1));

        Button_Issue.setMnemonic('i');
        Button_Issue.setText("Issue Selected");
        Button_Issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_IssueActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 309, 140, -1));

        Button_Cancel.setBackground(new java.awt.Color(204, 0, 0));
        Button_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Button_Cancel.setMnemonic('c');
        Button_Cancel.setText("Cancel");
        Button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 349, 140, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("         Welcome to IUT Library Management System!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 624, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_searchMouseClicked
        // TODO add your handling code here:
        int rows=Table_search.getSelectedRow();
        table_info=new String[5];
        table_info[0]=(Table_search.getModel().getValueAt(rows,0).toString());
        
    }//GEN-LAST:event_Table_searchMouseClicked

    private void Button_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SearchActionPerformed
        // TODO add your handling code here:
        dtm= new DefaultTableModel();
        Action();

    }//GEN-LAST:event_Button_SearchActionPerformed

    private void Button_IssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_IssueActionPerformed
        // TODO add your handling code here:
        DB_Connect.Issue(table_info);
        dtm= new DefaultTableModel();
        Action();
            
       
    }//GEN-LAST:event_Button_IssueActionPerformed

    private void Button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Home_User home=new Home_User();
        home.setVisible(true);
    }//GEN-LAST:event_Button_CancelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancel;
    private javax.swing.JButton Button_Issue;
    private javax.swing.JButton Button_Search;
    private javax.swing.JRadioButton RB_Author;
    private javax.swing.JRadioButton RB_Name;
    private javax.swing.JRadioButton RB_Publisher;
    private javax.swing.JTable Table_search;
    private javax.swing.JTextField Value;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
