/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;
import java.awt.event.WindowEvent;

public class Login extends javax.swing.JFrame{
    public String username;
    public String password;
    public String User_Type;
    public boolean b;
    /**
     * Creates new form Login
     */
    public Login() {
        b=false;
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group_User_Type = new javax.swing.ButtonGroup();
        Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Username_value = new javax.swing.JTextField();
        Button_login = new javax.swing.JButton();
        Button_cancel = new javax.swing.JButton();
        Button_Admin = new javax.swing.JRadioButton();
        Button_User = new javax.swing.JRadioButton();
        Password_value = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        Button_Sign_In_Login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(280, 120));
        setName("Login_frame"); // NOI18N
        setResizable(false);

        Login.setBackground(new java.awt.Color(79, 77, 77));
        Login.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.red));
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setMinimumSize(new java.awt.Dimension(800, 480));
        Login.setName("LOGIN"); // NOI18N
        Login.setOpaque(false);
        Login.setPreferredSize(new java.awt.Dimension(800, 480));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN AS");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 90, -1));

        Username.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        Login.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        Password.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        Login.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 75, -1));

        Username_value.setOpaque(true);
        Username_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_valueActionPerformed(evt);
            }
        });
        Login.add(Username_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 230, -1));

        Button_login.setBackground(new java.awt.Color(0, 153, 255));
        Button_login.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        Button_login.setForeground(new java.awt.Color(255, 255, 255));
        Button_login.setMnemonic('l');
        Button_login.setText("Login");
        Button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_loginActionPerformed(evt);
            }
        });
        Login.add(Button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 140, -1));

        Button_cancel.setBackground(new java.awt.Color(204, 0, 0));
        Button_cancel.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        Button_cancel.setForeground(new java.awt.Color(255, 255, 255));
        Button_cancel.setMnemonic('c');
        Button_cancel.setText("Cancel");
        Button_cancel.setPreferredSize(new java.awt.Dimension(65, 28));
        Button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cancelActionPerformed(evt);
            }
        });
        Login.add(Button_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 130, -1));

        Button_Admin.setBackground(new java.awt.Color(79, 77, 77));
        Group_User_Type.add(Button_Admin);
        Button_Admin.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        Button_Admin.setForeground(new java.awt.Color(255, 255, 255));
        Button_Admin.setMnemonic('a');
        Button_Admin.setText("Admin");
        Button_Admin.setContentAreaFilled(false);
        Button_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AdminActionPerformed(evt);
            }
        });
        Login.add(Button_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        Button_User.setBackground(new java.awt.Color(79, 77, 77));
        Group_User_Type.add(Button_User);
        Button_User.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        Button_User.setForeground(new java.awt.Color(255, 255, 255));
        Button_User.setMnemonic('e');
        Button_User.setText("Client");
        Button_User.setContentAreaFilled(false);
        Button_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_UserActionPerformed(evt);
            }
        });
        Login.add(Button_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        Password_value.setOpaque(true);
        Login.add(Password_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 260, 230, -1));

        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Don't have an account?");
        Login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 170, -1));

        Button_Sign_In_Login.setBackground(new java.awt.Color(0, 153, 0));
        Button_Sign_In_Login.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        Button_Sign_In_Login.setForeground(new java.awt.Color(255, 255, 255));
        Button_Sign_In_Login.setMnemonic('r');
        Button_Sign_In_Login.setText("Create Account");
        Button_Sign_In_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Sign_In_LoginActionPerformed(evt);
            }
        });
        Login.add(Button_Sign_In_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 150, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/index.jpg"))); // NOI18N
        jLabel4.setOpaque(true);
        Login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, 290));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOGIN");
        Login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));
        Login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1024, 1024));
        Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    @SuppressWarnings("deprecation")
    private void Button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_loginActionPerformed
        // TODO add your handling code here:
       
              username=Username_value.getText();
              password=Password_value.getText();
              DB_Connect.LogIn(User_Type,username,password);
              this.dispose();
    }//GEN-LAST:event_Button_loginActionPerformed
    private void Button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Button_cancelActionPerformed
    private void Username_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_valueActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_Username_valueActionPerformed
    private void Button_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AdminActionPerformed
        // TODO add your handling code here:
        User_Type=Button_Admin.getText();
    }//GEN-LAST:event_Button_AdminActionPerformed
    private void Button_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_UserActionPerformed
        // TODO add your handling code here:
        User_Type=Button_User.getText();
    }//GEN-LAST:event_Button_UserActionPerformed

    private void Button_Sign_In_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Sign_In_LoginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Open_Account open=new Open_Account();
        open.setVisible(true);
    }//GEN-LAST:event_Button_Sign_In_LoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Button_Admin;
    private javax.swing.JButton Button_Sign_In_Login;
    private javax.swing.JRadioButton Button_User;
    private javax.swing.JButton Button_cancel;
    private javax.swing.JButton Button_login;
    private javax.swing.ButtonGroup Group_User_Type;
    private javax.swing.JPanel Login;
    private javax.swing.JLabel Password;
    private static javax.swing.JPasswordField Password_value;
    private javax.swing.JLabel Username;
    private static javax.swing.JTextField Username_value;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}