/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sunef
 */
public class Return extends javax.swing.JFrame {
    public String Val;
    public int choice;
    public int c=0;
    public DefaultTableModel  dtm;
    public String[][] info=null;
    public String[] table_info=null;
    /**
     * Creates new form Return
     */
    public Return() {
        initComponents();
        Action();
    }
public void Action(){
   
        info=DB_Connect.View_Issued();
        String[] Columns={"BOOK_ID","BOOK_GID","TITLE","AUTHOR"};
        DefaultTableModel dtm= new DefaultTableModel();
        dtm.setColumnIdentifiers(Columns);
        
        if(info!=null){    
            for(int row=0;row<info.length;row++){
                    String[] rows={ info[row][0],info[row][1],info[row][2],info[row][3]};
                    dtm.addRow(rows);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"No records to view!","Empty Record", JOptionPane.INFORMATION_MESSAGE);
        }
        Table_view.setModel(dtm);       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_view = new javax.swing.JTable();
        Button_return = new javax.swing.JButton();
        Button_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 120));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("        Welcome to IUT Library Management System!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 27, 624, -1));

        Table_view.setBackground(new java.awt.Color(51, 51, 51));
        Table_view.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Table_view.setForeground(new java.awt.Color(255, 255, 255));
        Table_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_viewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_view);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 107, 683, 293));

        Button_return.setMnemonic('r');
        Button_return.setText("Return Selected");
        Button_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_returnActionPerformed(evt);
            }
        });
        jPanel1.add(Button_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 427, 163, -1));

        Button_cancel.setBackground(new java.awt.Color(204, 0, 0));
        Button_cancel.setForeground(new java.awt.Color(255, 255, 255));
        Button_cancel.setMnemonic('c');
        Button_cancel.setText("Cancel");
        Button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(Button_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 427, 151, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_returnActionPerformed
        // TODO add your handling code here:
        
        DB_Connect.Return(table_info);
        dtm= new DefaultTableModel();
        Action();
    }//GEN-LAST:event_Button_returnActionPerformed

    private void Table_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_viewMouseClicked
        // TODO add your handling code here:
        
        int rows=Table_view.getSelectedRow();
        table_info=new String[5];
        for(int i=0;i<5;i++){
            table_info[i]=(Table_view.getModel().getValueAt(rows,i).toString());
        }
        
    }//GEN-LAST:event_Table_viewMouseClicked

    private void Button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cancelActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        Home_User home=new Home_User();
        home.setVisible(true);
    }//GEN-LAST:event_Button_cancelActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_cancel;
    private javax.swing.JButton Button_return;
    private javax.swing.JTable Table_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
