/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sunef
 */
public class Search extends javax.swing.JFrame {
    public String Val;
    public int choice;
    public DefaultTableModel  dtm;
   
    public String[] Columns={"Group_ID","TITLE","AUTHOR","PUBLISHER","NO. OF COPIES"};
        
    /**
     * Creates new form Search
     */
    public int user=-1;
    public Search(int i) {
        initComponents();
        user=i;
       }
    public void Action(){
        if(RB_Author.isSelected())choice=1;
        else if(RB_Name.isSelected())choice=2;
        else if(RB_Publisher.isSelected())choice=3;
       Val=Value.getText();
       
        String[][] info=DB_Connect.getVAL(Val, choice);
//        for(int row=0;row<info.length;row++){
//            System.out.printf("%s %s %s %s %s \n", info[row][0],info[row][1],info[row][2],info[row][3],info[row][4]);
//        }
        
       dtm.setColumnIdentifiers(Columns);
       for(int row=0;row<info.length;row++){
            String[] rows={ info[row][0],info[row][1],info[row][2],info[row][3],info[row][4]};
            dtm.addRow(rows);//sl No.,title,author,pubname,copy
        }
       dtm.fireTableDataChanged();
        Table_search.setModel(dtm);
     
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RB_Name = new javax.swing.JRadioButton();
        RB_Publisher = new javax.swing.JRadioButton();
        RB_Author = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        Value = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_search = new javax.swing.JTable();
        Button_Search = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 120));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("        Welcome to IUT Library Management System!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 31, 624, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search By");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        RB_Name.setBackground(new java.awt.Color(79, 77, 77));
        buttonGroup1.add(RB_Name);
        RB_Name.setForeground(new java.awt.Color(255, 255, 255));
        RB_Name.setMnemonic('b');
        RB_Name.setText("Book Name");
        RB_Name.setContentAreaFilled(false);
        RB_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_NameActionPerformed(evt);
            }
        });
        jPanel1.add(RB_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        RB_Publisher.setBackground(new java.awt.Color(79, 77, 77));
        buttonGroup1.add(RB_Publisher);
        RB_Publisher.setForeground(new java.awt.Color(255, 255, 255));
        RB_Publisher.setMnemonic('p');
        RB_Publisher.setText("Publisher Name");
        RB_Publisher.setContentAreaFilled(false);
        RB_Publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_PublisherActionPerformed(evt);
            }
        });
        jPanel1.add(RB_Publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        RB_Author.setBackground(new java.awt.Color(79, 77, 77));
        buttonGroup1.add(RB_Author);
        RB_Author.setForeground(new java.awt.Color(255, 255, 255));
        RB_Author.setMnemonic('a');
        RB_Author.setSelected(true);
        RB_Author.setText("Author Name");
        RB_Author.setContentAreaFilled(false);
        RB_Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_AuthorActionPerformed(evt);
            }
        });
        jPanel1.add(RB_Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Value");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        Value.setOpaque(true);
        Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueActionPerformed(evt);
            }
        });
        jPanel1.add(Value, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 197, -1));

        Table_search.setAutoCreateRowSorter(true);
        Table_search.setBackground(new java.awt.Color(51, 51, 51));
        Table_search.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Table_search.setForeground(new java.awt.Color(255, 255, 255));
        Table_search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Group_ID", "Title", "Author", "Publisher", "Copies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_search.setEnabled(false);
        jScrollPane1.setViewportView(Table_search);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 530, 310));

        Button_Search.setMnemonic('s');
        Button_Search.setText("Search");
        Button_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Button_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        Cancel.setBackground(new java.awt.Color(204, 0, 0));
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setMnemonic('c');
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        if(user==1){
            this.dispose();
            Home_Admin home=new Home_Admin();
            home.setVisible(true);
        }
        else{
            this.dispose();
            Home_User home=new Home_User();
            home.setVisible(true);
        }
    }//GEN-LAST:event_CancelActionPerformed

    private void RB_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_AuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_AuthorActionPerformed

    private void RB_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_NameActionPerformed

    private void RB_PublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_PublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_PublisherActionPerformed

    private void ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ValueActionPerformed

    private void Button_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SearchActionPerformed
        dtm= new DefaultTableModel();
        Action();
    }//GEN-LAST:event_Button_SearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Search;
    private javax.swing.JButton Cancel;
    private javax.swing.JRadioButton RB_Author;
    private javax.swing.JRadioButton RB_Name;
    private javax.swing.JRadioButton RB_Publisher;
    private javax.swing.JTable Table_search;
    private javax.swing.JTextField Value;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
