/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sunef
 */
public class Viewbooks extends javax.swing.JFrame {

    /**
     * Creates new form Viewbooks
     */
    public Viewbooks() {
        initComponents();
        Action();
      }
    public void Action(){
        
        String[][] info=DB_Connect.getBookInfo();
        String[] Columns={"G_ID","TITLE","AUTHOR","NO. OF COPIES","PUBLISHER"};
        DefaultTableModel dtm= new DefaultTableModel();
        dtm.setColumnIdentifiers(Columns);
        if(info==null){    
            JOptionPane.showMessageDialog(null,"No records to view!","Empty Record", JOptionPane.INFORMATION_MESSAGE);
            
        }
        else{
            for(int row=0;row<info.length;row++){
                String[] rows={ info[row][0],info[row][2],info[row][3],info[row][4],info[row][1]};
                dtm.addRow(rows);//gid,title,author,copy,pubname
            }
        }
        viewbooks_table.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewbooks_table = new javax.swing.JTable();
        Button_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 120));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewbooks_table.setBackground(new java.awt.Color(51, 51, 51));
        viewbooks_table.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        viewbooks_table.setForeground(new java.awt.Color(255, 255, 255));
        viewbooks_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        viewbooks_table.setEnabled(false);
        jScrollPane1.setViewportView(viewbooks_table);
        viewbooks_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 113, 747, 270));

        Button_back.setBackground(new java.awt.Color(204, 0, 0));
        Button_back.setForeground(new java.awt.Color(255, 255, 255));
        Button_back.setText("Back");
        Button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_backActionPerformed(evt);
            }
        });
        jPanel1.add(Button_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 411, 79, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("        Welcome to IUT Library Management System!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 31, 624, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Home_Admin home= new Home_Admin();
        home.setVisible(true);
    }//GEN-LAST:event_Button_backActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_back;
    private javax.swing.JButton Button_back1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable viewbooks_table;
    private javax.swing.JTable viewbooks_table1;
    // End of variables declaration//GEN-END:variables
}
