/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sunef
 */
public class ViewIssued extends javax.swing.JFrame {

    /**
     * Creates new form ViewIssued
     */
    String[][] info=new String[5][7];
    public ViewIssued() {
        initComponents();
        Action();
    }
    public void Action(){
        info=DB_Connect.View_Issued();
        String[] Columns={"BOOK_ID","BOOK_GID","TITLE","AUTHOR"};
        DefaultTableModel dtm= new DefaultTableModel();
        dtm.setColumnIdentifiers(Columns);
        
        if(info==null){    
            JOptionPane.showMessageDialog(null,"No records to view!","Empty Record", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            
            for(int row=0;row<info.length;row++){
                    String[] rows={ info[row][0],info[row][1],info[row][2],info[row][3]};
                    dtm.addRow(rows);
                    TF_name.setText(info[row][4]);
                    TF_memID.setText(info[row][5]);
                    TF_type.setText(info[row][6]);
            }
       
        }
        Table_view.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_memID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_view = new javax.swing.JTable();
        Button_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_type = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 120));
        setMinimumSize(new java.awt.Dimension(800, 480));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 109, -1, -1));

        TF_name.setEditable(false);
        TF_name.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        TF_name.setEnabled(false);
        jPanel1.add(TF_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 103, 183, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 149, -1, -1));

        TF_memID.setEditable(false);
        TF_memID.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        TF_memID.setEnabled(false);
        jPanel1.add(TF_memID, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 143, 183, -1));

        Table_view.setBackground(new java.awt.Color(51, 51, 51));
        Table_view.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Table_view.setForeground(new java.awt.Color(255, 255, 255));
        Table_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK_ID", "BOOK_GID", "TITLE", "AUTHOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_view.setEnabled(false);
        Table_view.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(Table_view);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 268));

        Button_back.setBackground(new java.awt.Color(204, 0, 0));
        Button_back.setForeground(new java.awt.Color(255, 255, 255));
        Button_back.setMnemonic('b');
        Button_back.setText("Back");
        Button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_backActionPerformed(evt);
            }
        });
        jPanel1.add(Button_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 337, 75, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("        Welcome to IUT Library Management System!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 624, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 189, -1, -1));

        TF_type.setEditable(false);
        TF_type.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        TF_type.setEnabled(false);
        jPanel1.add(TF_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 183, 183, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/Login.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Home_User home=new Home_User();
        home.setVisible(true);
    }//GEN-LAST:event_Button_backActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_back;
    private javax.swing.JTextField TF_memID;
    private javax.swing.JTextField TF_name;
    private javax.swing.JTextField TF_type;
    private javax.swing.JTable Table_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
